<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>表格中的元素</description>
   <name>tr_td</name>
   <tag></tag>
   <elementGuidId>c0da7a20-7d98-4527-8271-c29ef841c4f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='mainContent']/div[2]/div[2]/div[2]/div[2]/div/div[2]/table/tbody/tr[1]/td[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div[2]/div[2]/div[2]/div[2]/div/div[2]/table/tbody/tr[1]/td[1]</value>
   </webElementProperties>
</WebElementEntity>
